# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dab9a335c0b5c7a7b962de3751da8e6444861b1ed811847705d170ca979c67247fc97640abda7e55fa0b9dca1c0b42481d36720abd82811be7d622ea4916933

test:
  secret_key_base: 9abb20b72417f51e1112a789085a5f8ba7911b745c4d66a7840140efc93bd1fdb009d22c8a88c6a627479b9b01f16c0f26237ed3fe8e85e1c99f6666e05fd84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
